# NCP Object Storage 설정
ncp.object-storage.accessKey=ncp_iam_BPAMKR3fx05Us6eZboXT
ncp.object-storage.secretKey=ncp_iam_BPKMKRT5i7oanG9xNyiWTzVHYa6SbomuQL
ncp.object-storage.endpoint=https://kr.object.ncloudstorage.com
ncp.object-storage.region=kr-standard

# API 설정
rest.api.file-uploader.path=http://110.165.19.107:8098

# Swagger Setting
springdoc.packages-to-scan=com.busan.dataetl
springdoc.swagger-ui.path=/swagger/api-docs/ui/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=false
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.filter=true
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.groups.enabled=true
springdoc.default-consumes-media-type=application/json;charset=UTF-8
springdoc.default-produces-media-type=application/json;charset=UTF-8
springdoc.cache.disabled=true