# NCP Object Storage 설정
ncp.object-storage.accessKey=ncp_iam_BPAMKR3fx05Us6eZboXT
ncp.object-storage.secretKey=ncp_iam_BPKMKRT5i7oanG9xNyiWTzVHYa6SbomuQL
ncp.object-storage.endpoint=https://kr.object.ncloudstorage.com
ncp.object-storage.region=kr-standard

# API 설정
rest.api.file-uploader.path=http://110.165.19.107:8098